FROM alpine:latest

RUN apk add --no-cache bash curl openjdk11-jre

COPY scripts/download_detect.sh /opt/

RUN chmod +x /opt/download_detect.sh

RUN /opt/download_detect.sh

COPY release/linux/arm64/blackduck-plugin /bin/

ENTRYPOINT ["/bin/blackduck-plugin"]