FROM plugins/base:windows-ltsc2022-amd64

USER ContainerAdministrator

ENV GODEBUG=netdns=go

COPY scripts/download_detect.ps1 C:\opt\

RUN powershell -File C:\opt\download_detect.ps1

COPY release/windows/amd64/blackduck-plugin.exe C:\bin\

ENTRYPOINT ["C:\\bin\\blackduck-plugin.exe"]